// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tomeshelf.Fitbit.Infrastructure;

#nullable disable

namespace Tomeshelf.Infrastructure.Persistence.Fitbit.Migrations
{
    [DbContext(typeof(TomeshelfFitbitDbContext))]
    [Migration("20260127165040_DropFitbitCredentials")]
    partial class DropFitbitCredentials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tomeshelf.Fitbit.Domain.FitbitDailySnapshot", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Bedtime")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double?>("BodyFatPercentage")
                        .HasColumnType("float");

                    b.Property<int?>("BurnedCalories")
                        .HasColumnType("int");

                    b.Property<double?>("CarbsGrams")
                        .HasColumnType("float");

                    b.Property<double?>("ChangeWeightKg")
                        .HasColumnType("float");

                    b.Property<double?>("CurrentWeightKg")
                        .HasColumnType("float");

                    b.Property<double?>("DistanceKm")
                        .HasColumnType("float");

                    b.Property<double?>("FatGrams")
                        .HasColumnType("float");

                    b.Property<double?>("FiberGrams")
                        .HasColumnType("float");

                    b.Property<int?>("Floors")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("GeneratedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("IntakeCalories")
                        .HasColumnType("int");

                    b.Property<double?>("LeanMassKg")
                        .HasColumnType("float");

                    b.Property<int?>("NetCalories")
                        .HasColumnType("int");

                    b.Property<double?>("ProteinGrams")
                        .HasColumnType("float");

                    b.Property<int?>("SleepDeepMinutes")
                        .HasColumnType("int");

                    b.Property<double?>("SleepEfficiencyPercentage")
                        .HasColumnType("float");

                    b.Property<int?>("SleepLightMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("SleepRemMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("SleepWakeMinutes")
                        .HasColumnType("int");

                    b.Property<double?>("SodiumMilligrams")
                        .HasColumnType("float");

                    b.Property<double?>("StartingWeightKg")
                        .HasColumnType("float");

                    b.Property<int?>("Steps")
                        .HasColumnType("int");

                    b.Property<double?>("TotalAwakeHours")
                        .HasColumnType("float");

                    b.Property<double?>("TotalSleepHours")
                        .HasColumnType("float");

                    b.Property<string>("WakeTime")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Date");

                    b.HasIndex("GeneratedUtc");

                    b.ToTable("FitbitDailySnapshots", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
