// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Tomeshelf.Infrastructure.Shared.Persistence;

#nullable disable

namespace Tomeshelf.Infrastructure.Persistence.Fitbit.Migrations
{
    /// <inheritdoc />
    [Migration("20251015000000_CreateFitbitSnapshotsSchema")]
    [DbContext(typeof(TomeshelfFitbitDbContext))]
    public partial class CreateFitbitSnapshotsSchema : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "FitbitDailySnapshots",
                columns: table => new
                {
                    Date = table.Column<DateTime>(type: "date", nullable: false),
                    GeneratedUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    StartingWeightKg = table.Column<double>(type: "float", nullable: true),
                    CurrentWeightKg = table.Column<double>(type: "float", nullable: true),
                    ChangeWeightKg = table.Column<double>(type: "float", nullable: true),
                    IntakeCalories = table.Column<int>(type: "int", nullable: true),
                    BurnedCalories = table.Column<int>(type: "int", nullable: true),
                    NetCalories = table.Column<int>(type: "int", nullable: true),
                    TotalSleepHours = table.Column<double>(type: "float", nullable: true),
                    TotalAwakeHours = table.Column<double>(type: "float", nullable: true),
                    SleepEfficiencyPercentage = table.Column<double>(type: "float", nullable: true),
                    Bedtime = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    WakeTime = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    Steps = table.Column<int>(type: "int", nullable: true),
                    DistanceKm = table.Column<double>(type: "float", nullable: true),
                    Floors = table.Column<int>(type: "int", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FitbitDailySnapshots", x => x.Date);
                });

            migrationBuilder.CreateIndex(
                name: "IX_FitbitDailySnapshots_GeneratedUtc",
                table: "FitbitDailySnapshots",
                column: "GeneratedUtc");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "FitbitDailySnapshots");
        }
    }
}
