// <auto-generated />
#nullable disable

using System;

namespace Tomeshelf.MCM.Infrastructure.Mcm
{
    [DbContext(typeof(TomeshelfMcmDbContext))]
    [Migration("20260102120000_AddGuestTimestamps")]
    partial class AddGuestTimestamps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tomeshelf.Domain.Entities.Mcm.EventEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("Tomeshelf.Domain.Entities.Mcm.GuestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("EventId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("GuestInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Guests", (string)null);
                });

            modelBuilder.Entity("Tomeshelf.Domain.Entities.Mcm.GuestInfoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DaysAppearing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KnownFor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GuestId")
                        .IsUnique();

                    b.ToTable("GuestInformation", (string)null);
                });

            modelBuilder.Entity("Tomeshelf.Domain.Entities.Mcm.GuestSocial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviantArt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facebook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fandom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GuestInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Imdb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instagram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Snapchat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tumblr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Twitch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Twitter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YouTube")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GuestInfoId")
                        .IsUnique();

                    b.ToTable("GuestSocials", (string)null);
                });

            modelBuilder.Entity("Tomeshelf.Domain.Entities.Mcm.GuestEntity", b =>
                {
                    b.HasOne("Tomeshelf.Domain.Entities.Mcm.EventEntity", "Event")
                        .WithMany("Guests")
                        .HasForeignKey("EventId");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Tomeshelf.Domain.Entities.Mcm.GuestInfoEntity", b =>
                {
                    b.HasOne("Tomeshelf.Domain.Entities.Mcm.GuestEntity", "Guest")
                        .WithOne("Information")
                        .HasForeignKey("Tomeshelf.Domain.Entities.Mcm.GuestInfoEntity", "GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("Tomeshelf.Domain.Entities.Mcm.GuestSocial", b =>
                {
                    b.HasOne("Tomeshelf.Domain.Entities.Mcm.GuestInfoEntity", "GuestInfo")
                        .WithOne("Socials")
                        .HasForeignKey("Tomeshelf.Domain.Entities.Mcm.GuestSocial", "GuestInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuestInfo");
                });

            modelBuilder.Entity("Tomeshelf.Domain.Entities.Mcm.EventEntity", b =>
                {
                    b.Navigation("Guests");
                });

            modelBuilder.Entity("Tomeshelf.Domain.Entities.Mcm.GuestEntity", b =>
                {
                    b.Navigation("Information");
                });

            modelBuilder.Entity("Tomeshelf.Domain.Entities.Mcm.GuestInfoEntity", b =>
                {
                    b.Navigation("Socials");
                });
#pragma warning restore 612, 618
        }
    }
}
